biodivui:
  image: diogok/apache
  links:
    - elasticsearch:elasticsearch
  ports:
    - 8081:80
  volumes:
    - .:/var/www
elasticsearch:
  image: diogok/elasticsearch
  ports:
    - 9200:9200
  volumes:
    - /var/data/dwc-elasticsearch/data:/usr/share/elasticsearch/data:rw
