version: "2"
services:
  #dwcbot:
  #  image: diogok/dwc-bot-es
  #  environment:
  #    ELASTICSEARCH: http://elasticsearch:9200
  #    INDEX: dwc
  elasticsearch:
    image: diogok/elasticsearch
    ports:
      - 9200:9200
    volumes:
      - /var/data/dwc-elasticsearch/data:/usr/share/elasticsearch/data:rw
